[tool.black]
line-length = 100

[tool.ruff]
select = ["E", "F", "W", "I", "S", "B", "RUF"]
line-length = 100
target-version = "py310"

[tool.ruff.per-file-ignores]
"collect-data-from-datagrepper.py" = ["S608"]
"collect-data-from-db.py" = ["S608"]
"query-monthly-data.py" = ["S608"]
